name: nnunet_gpu

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip=23.1
  - pip:
    - acvl-utils==0.2
    - batchgenerators==0.25
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - cmake==3.26.3
    - connected-components-3d==3.10.5
    - contourpy==1.0.7
    - cycler==0.11.0
    - dicom2nifti==2.4.8
    - dynamic-network-architectures==0.2
    - filelock==3.12.0
    - fonttools==4.39.3
    - future==0.18.3
    - graphviz==0.20.1
    - idna==3.4
    - imagecodecs==2023.3.16
    - imageio==2.27.0
    - importlib-resources==5.12.0
    - Jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy_loader==0.2
    - linecache2==1.0.0
    - lit==16.0.1
    - MarkupSafe==2.1.2
    - matplotlib==3.7.1
    - MedPy==0.4.0
    - mpmath==1.3.0
    - networkx==3.1
    - nibabel==5.1.0
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - packaging==23.1
    - pandas==2.0.0
    - Pillow==9.5.0
    - pydicom==2.3.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-gdcm==3.0.21
    - pytz==2023.3
    - PyWavelets==1.4.1
    - PyYAML==6.0
    - requests==2.28.2
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - seaborn==0.12.2
    - SimpleITK==2.2.1
    - six==1.16.0
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - torch==2.0.0
    - tqdm==4.65.0
    - traceback2==1.4.0
    - triton==2.0.0
    - typing_extensions==4.5.0
    - tzdata==2023.3
    - unittest2==1.1.0
    - urllib3==1.26.15
    - yacs==0.1.8
    - zipp==3.15.0